### ISSUE TITLE
ARCamera not working

### ISSUE THREAD

**Issue by ManChrys** [creativehims/UX-Plane-AR#1]
Hello my friend and happy new year.

Nice project for the Android devices, but i have an issue. 

When im using it on my project 

1) on game windows i see that

![4](https://user-images.githubusercontent.com/67521662/103965769-25a53f00-5167-11eb-9b47-a32b82350714.png)

It says look for more textures.

 In your project, which one works fine, the same windows looks like that.

![5](https://user-images.githubusercontent.com/67521662/103965880-5a18fb00-5167-11eb-9d1f-1b858a70fc14.png)

2) when im building my apk with no errors my phone's camera is black and still saying exact the same thing with the game window 

![4](https://user-images.githubusercontent.com/67521662/103965769-25a53f00-5167-11eb-9b47-a32b82350714.png)

So i think its something with AR Camera but i build it exact the same with yours. When im starting the apk on the phone it doesnt even ask for camera permission its just like a photo nothing is moving.

Thanks in advance.

**Comment by devhims** [comment]
Hi @ManChrys ,

Could you go to project settings and confirm if ARCore is checked for Android in XR Plug-in Management? 

<img width="624" alt="Screenshot 2021-01-08 at 9 26 03 AM" src="https://user-images.githubusercontent.com/17825870/103972855-f8bb5100-5193-11eb-8675-2901d9493748.png">

Since the AR Camera doesn't work in the editor, you'll see the default Ui with the black background. So, that's nothing to worry about. It should work fine on the device and I just tested it.

**Comment by ManChrys** [comment]
@creativehims Hello my friend.

First of all thanks for your quick response.You were right when i enabled it AR Camera worked fine, but then something else happened.

Im making an AR Portal with Pointcloud. So when im under the Portal i want to spawn the PointCloud. This is working but when im using UX to start the project, when im going through the door everything dissapeared.

Im sending you the project with UI and the original project. Im sorry if i waste your time but i feel that im so close and always something goes wrong :( 

I send the files to your email ( thinktank.himanshu@gmail.com ) through wetransfer.


I would be thankful if you could help me.

**Comment by devhims** [comment]
I'm sorry mate, I tried opening your project `arportal_UX` 3 separate times on my mac and it crashed the system each time. There is something wrong with the files.

 As for your problem, it seems to be an issue with the camera setup. I've no clue how your portal works, but you've to make sure it doesn't hinder the working of the AR Camera object.

**Comment by ManChrys** [comment]
That's strange I just tried on my pcs(windows and Ubuntu)and opened normally. Ok my friend I'll try to find what's going on here . Wish me luck. Have a nice weekend.

**Comment by ManChrys** [comment]
@creativehims 

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

public class Portal : MonoBehaviour
{
    public Material[] materials;

    // Start is called before the first frame update
    void Start()
    {
        foreach (var mat in materials)
        {
            mat.SetInt("stest", (int)CompareFunction.Equal);
        }
    }

    // Update is called once per frame
    void Update()
    {

    }



    private void OnTriggerStay(Collider collider)
    {
        if (collider.tag != "MainCamera")
        {
            return;
        }


        Vector3 user_position = Camera.main.transform.position + Camera.main.transform.forward * Camera.main.nearClipPlane;
        Vector3 relativePosition = transform.InverseTransformPoint(user_position);


        //outside
        if (relativePosition.z < 0)
        {
            foreach (var mat in materials)
            {
                mat.SetInt("stest", (int)CompareFunction.Equal);
            }

        }
        //inside
        else
        {
            foreach (var mat in materials)
            {
                mat.SetInt("stest", (int)CompareFunction.NotEqual);
            }


        }
    }

}`

thats my portal script if you see somthing strange :P

**Comment by ManChrys** [comment]
Ok its fixed . The problem had nothing to do with this project.

See you my friend :D
